// Code generated by protoc-gen-go. DO NOT EDIT.
// source: biodata.proto

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	biodata.proto

It has these top-level messages:
	Biorequest
	Bioresponse
*/
package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Biorequest struct {
	EmailId string `protobuf:"bytes,1,opt,name=emailId" json:"emailId,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Age     int32  `protobuf:"varint,3,opt,name=age" json:"age,omitempty"`
}

func (m *Biorequest) Reset()                    { *m = Biorequest{} }
func (m *Biorequest) String() string            { return proto.CompactTextString(m) }
func (*Biorequest) ProtoMessage()               {}
func (*Biorequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Biorequest) GetEmailId() string {
	if m != nil {
		return m.EmailId
	}
	return ""
}

func (m *Biorequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Biorequest) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type Bioresponse struct {
	StatusResponse string `protobuf:"bytes,1,opt,name=statusResponse" json:"statusResponse,omitempty"`
	Status         bool   `protobuf:"varint,2,opt,name=status" json:"status,omitempty"`
}

func (m *Bioresponse) Reset()                    { *m = Bioresponse{} }
func (m *Bioresponse) String() string            { return proto.CompactTextString(m) }
func (*Bioresponse) ProtoMessage()               {}
func (*Bioresponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Bioresponse) GetStatusResponse() string {
	if m != nil {
		return m.StatusResponse
	}
	return ""
}

func (m *Bioresponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*Biorequest)(nil), "biodata.biorequest")
	proto.RegisterType((*Bioresponse)(nil), "biodata.bioresponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Info service

type InfoClient interface {
	Details(ctx context.Context, in *Biorequest, opts ...grpc.CallOption) (*Bioresponse, error)
}

type infoClient struct {
	cc *grpc.ClientConn
}

func NewInfoClient(cc *grpc.ClientConn) InfoClient {
	return &infoClient{cc}
}

func (c *infoClient) Details(ctx context.Context, in *Biorequest, opts ...grpc.CallOption) (*Bioresponse, error) {
	out := new(Bioresponse)
	err := grpc.Invoke(ctx, "/biodata.Info/Details", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Info service

type InfoServer interface {
	Details(context.Context, *Biorequest) (*Bioresponse, error)
}

func RegisterInfoServer(s *grpc.Server, srv InfoServer) {
	s.RegisterService(&_Info_serviceDesc, srv)
}

func _Info_Details_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Biorequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoServer).Details(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/biodata.Info/Details",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoServer).Details(ctx, req.(*Biorequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Info_serviceDesc = grpc.ServiceDesc{
	ServiceName: "biodata.Info",
	HandlerType: (*InfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Details",
			Handler:    _Info_Details_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "biodata.proto",
}

func init() { proto.RegisterFile("biodata.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xcf, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x5d, 0x5b, 0xbb, 0x3a, 0xfe, 0x40, 0x46, 0x91, 0xe0, 0xa9, 0xec, 0x41, 0x7a, 0xca,
	0xc1, 0x82, 0x47, 0x0f, 0x8b, 0x97, 0x82, 0x42, 0xc9, 0xd1, 0xdb, 0xac, 0x1d, 0x97, 0xc0, 0x66,
	0x13, 0x77, 0x52, 0xf0, 0xcf, 0x97, 0x66, 0xb3, 0x88, 0xde, 0xde, 0xfb, 0x08, 0x1f, 0x99, 0x07,
	0x97, 0x8d, 0xf5, 0x3b, 0x8a, 0xa4, 0xc3, 0xe0, 0xa3, 0xc7, 0x32, 0xd7, 0xea, 0x15, 0xa0, 0xb1,
	0x7e, 0xe0, 0xaf, 0x3d, 0x4b, 0x44, 0x05, 0x25, 0x3b, 0xb2, 0xdd, 0x66, 0xa7, 0x8a, 0x65, 0xb1,
	0x3a, 0x33, 0x53, 0x45, 0x84, 0x79, 0x4f, 0x8e, 0xd5, 0x71, 0xc2, 0x29, 0xe3, 0x35, 0xcc, 0xa8,
	0x65, 0x35, 0x5b, 0x16, 0xab, 0x13, 0x73, 0x88, 0xd5, 0x1b, 0x9c, 0x27, 0x9b, 0x04, 0xdf, 0x0b,
	0xe3, 0x03, 0x5c, 0x49, 0xa4, 0xb8, 0x17, 0x93, 0x49, 0xb6, 0xfe, 0xa3, 0x78, 0x07, 0x8b, 0x91,
	0x24, 0xfd, 0xa9, 0xc9, 0xed, 0xf1, 0x19, 0xe6, 0x9b, 0xfe, 0xd3, 0xe3, 0x13, 0x94, 0x2f, 0x1c,
	0xc9, 0x76, 0x82, 0x37, 0x7a, 0x3a, 0xe4, 0xf7, 0xdb, 0xf7, 0xb7, 0x7f, 0xe1, 0x68, 0xad, 0x8e,
	0xea, 0x35, 0x28, 0xeb, 0x75, 0x3b, 0x84, 0x0f, 0xcd, 0xdf, 0xe4, 0x42, 0xc7, 0x32, 0xbd, 0xac,
	0x2f, 0xea, 0x31, 0x6c, 0x0f, 0x7b, 0x6c, 0x8b, 0xf7, 0xd2, 0xb1, 0x08, 0xb5, 0xdc, 0x2c, 0xd2,
	0x42, 0xeb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf9, 0x24, 0x0d, 0xd6, 0x32, 0x01, 0x00, 0x00,
}
